on:
  push:
    branches:
    - kje
env:
  DOTNET_CORE_VERSION: 7.0.x
  CONTAINER_APP_NAME: bygspy-container-app
  CONTAINER_APP_ENVIRONMENT_NAME: managedEnv2024
  RESOURCE_GROUP: BygSpyResourceGroupDev
  CONTAINER_REGISTRY_NAME: bygspy2024
  CONTAINER_REGISTRY_LOGIN_SERVER: bygspy2024.azurecr.io
jobs:
  BuildAndDeployContainerApp:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.managedEnv2024_SPN }}
    - name: Container App deploy
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: ${{ github.workspace }}
        acrName: ${{ env.CONTAINER_REGISTRY_NAME }}
        acrUsername: ${{ secrets.BygSpy2024_USERNAME_440E }}
        acrPassword: ${{ secrets.BygSpy2024_PASSWORD_440E }}
        imageToBuild: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
        containerAppName: ${{ env.CONTAINER_APP_NAME }}
        containerAppEnvironment: ${{ env.CONTAINER_APP_ENVIRONMENT_NAME }}
        resourceGroup: ${{ env.RESOURCE_GROUP }}
