# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - BygSpyWebApp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://bygspy2024.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_b81c0c83e6954971ac807ff45b89a68a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c5d156d39fa341a3867bcdd1f2e3e410 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: bygspy2024.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b81c0c83e6954971ac807ff45b89a68a }}/bygspy:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'BygSpyWebApp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2380f3fc2660404ea30bb84be1e35526 }}
        images: 'bygspy2024.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b81c0c83e6954971ac807ff45b89a68a }}/bygspy:${{ github.sha }}'